version: "3.9"

services:
  web:
    restart: always
    image: registry.digitalocean.com/super-perfundo/super-perfundo:prod
    environment:
      - HOST=super-perfundo.tech
      - PORT=80
      - SECRET_KEY_BASE=$SECRET_KEY_BASE
      - VIRTUAL_HOST=www.superperfundo.tech,superperfundo.tech
      - LETSENCRYPT_HOST=www.superperfundo.com,superperfundo.tech

