on: 
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build_image:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0

      - name: Build container image
        run: docker build -t registry.digitalocean.com/super-perfundo/super-perfundo:prod .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/super-perfundo/super-perfundo:prod

  deploy:
    needs: build_image
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.4
        with:
          HOST: ${{ secrets.DIGITAL_OCEAN_HOST }}
          USERNAME: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          KEY: ${{ secrets.PRIVATE_SSH_KEY }}
          script: |
            cd super_perfundo
            git pull origin master
            docker-compose -f super-perfundo-prod-compose.yml stop
            docker-compose -f super-perfundo-prod-compose.yml rm -f
            docker-compose -f super-perfundo-prod-compose.yml pull
            docker-compose -f super-perfundo-prod-compose.yml up -d
