on: 
  pull_request:
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.2
          elixir-version: 1.13.1
      - name: Install deps
        run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test
