name: SuperPerfundo
on: 
  pull_request:
    branches:
      - master

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.3.2.2
          elixir-version: 1.14.5

      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test
