on: push
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 21.1
          elixir-version: 1.10.2
      - name: Install deps
        run: mix deps.get

      - run: mix format --check-formatted
      - run: mix test
