on: 
  pull_request:
    branches:
      - master

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 23.3.1
          elixir-version: 1.11.4

      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test
