on: 
  pull_request:
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 23.0.2
          elixir-version: 1.10.3
      - name: Install deps
        run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test
